# Используем официальный образ PostgreSQL
FROM postgres:latest

# Устанавливаем переменную окружения для пароля пользователя postgres
ENV POSTGRES_PASSWORD=231514

# Создаем базу данных с именем "carsharing"
ENV POSTGRES_DB=carsharing
